### PR TITLE
combining all the files into one page's worth of output

### PR DESCRIPTION
**Pull request by ktbartholomew**
@meker12 there may be elements of this PR that you don't want to accept (like my removal of **all** UI chrome in `layout.html`), but I wanted to get the PR opened so we can discuss and get the one-page format into the main repo.

### CODE REVIEW

**Comment by annegentle** [comment]
Removal of all UI chrome is, well, ugh. I do prefer no more hiddentoc for ease of walk-up contributors unfamiliar with the organization.

**Comment by meker12** [comment]
So I think we can have a theme for the local build that includes the UI stuff;  and then another that doesn't -- for the deconst build.   The conf.py supports applying themes based on conditions.

**Comment by ktbartholomew** [comment]
@meker12 that's probably the better approach. I'll add a commit to restore the UI.

**Comment by meker12** [comment]
That sounds good -- Thank you.   

After that, I can merge the pull request.   I agree with Anne that getting rid of the :hiddentoc: makes things less confusing.

**Comment by ktbartholomew** [comment]
@meker12 this should be mergeable now, after 914807c

**Pull request merged**
